//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public string SID { get; set; }
        public string NAME { get; set; }
        public string STD { get; set; }
        public int AGE { get; set; }
        public string ADDRESS { get; set; }
        public string FNAME { get; set; }
        public string MNAME { get; set; }
        public string TNAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> PHONE { get; set; }
    }
}
